### ISSUE TITLE
necessity of setting a marker

### ISSUE THREAD

**Issue by iham** [plone/plone.behavior#16]
i had troubles with a behavior i wrote and stumbled a bit more than usual ;)

behavior.py
```python
#schema
@provider(IFormFieldProvider)
class IMyBehavoir(model.Schema):
    field1 = ...
    field2 = ...

#factory
@implementer(IMyBehavior)
class MyBehavior(object):
    def __init__(self, context):
        self.context = context

    @property
    def attr1(self):
         return 'test'
```
configure.zcml
```xml
  <plone:behavior
      name="my.behavior"
      provides=".behavior.IMyBehavior"
      factory=".behavior.MyBehavior"
      marker=".behavior.IMyBehavior"
      />
```
on a view (self.context is a plone content object i applied the behavior to - which worked easily), when calling the attr1 i get an error:
```
>>> IMyBehavior(self.context).attr1
*** AttributeError: 'MyBehavior' object has no attribute 'attr1'
```

ok... not really a helpful traceback, but with a little hint from @agitator i changed the marker as it is not allowed to be the same interface as the schema interface:
behavior.py
```python
#marker
class IMyBehavoirMarker(Interface):
    pass

#schema
@provider(IFormFieldProvider)
class IMyBehavoir(model.Schema):
    field1 = ...
    field2 = ...

#factory
@implementer(IMyBehavior)
class MyBehavior(object):
    def __init__(self, context):
        self.context = context

    @property
    def attr1(self):
         return 'test'
```
configure.zcml
```xml
  <plone:behavior
      name="my.behavior"
      provides=".behavior.IMyBehavior"
      factory=".behavior.MyBehavior"
      marker=".behavior.IMyBehaviorMarker"
      />
```
```
>>> IMyBehavior(self.context).attr1
test
```
it works! yeah!

but then i thought about, why to have a marker interface at all, as i never touch or use it.
so i removed it completely:

behavior.py
```python
#schema
@provider(IFormFieldProvider)
class IMyBehavoir(model.Schema):
    field1 = ...
    field2 = ...

#factory
@implementer(IMyBehavior)
class MyBehavior(object):
    def __init__(self, context):
        self.context = context

    @property
    def attr1(self):
         return 'test'
```
configure.zcml
```xml
  <plone:behavior
      name="my.behavior"
      provides=".behavior.IMyBehavior"
      factory=".behavior.MyBehavior"
      />
```
```
>>> IMyBehavior(self.context).attr1
test
```
and it works **too**!

## so here are my confusion:
1.) why do i need a marker interface at all here?
2.) why does the traceback not tell me anything about it?
3.) why doesn't zope scream about it on start up?
4.) why is the documentation miss leading at that point?

to be more precise on 4.)
quoted from the docs:
> marker
> A marker interface to be applied by the behavior. If factory is not given, then this is optional and defaults to the value of provides. If factory is given **marker is required** and **should** be different from provides - **even if its not enforced**.

"marker is required" -> NO. it's not. my sample above shows that. no errors, no problems, functionality works fine.
"should" -> NO. it has to be (**if defined**). my sample shows that.
"even if its not enforced" -> NO. it **is** enforced.

and here comes my biggest confusion on this whole topic:
keeping in mind that the marker is optional and falls back to provides...
why does the code/registry work without a marker, but not with the same interface given???
isn't it basically the same "stunt"?
no marker value -> use provides value --> works
marker value same as provides value --> works NOT

... this gives me some headache and i hope, someone can help me to understand ;)
(i am not even sure if i found a bug or i am the bug - kafkaesque, isn't it ...)

**Comment by jensens** [comment]
1.) why do i need a marker interface at all here?

So, this is ZCA. In order to adapt a context with an adapter, context has to provide some interface (here a marker). The adapter should provide its own interface.

2.) why does the traceback not tell me anything about it?

Well. We may want to add some ``__traceback_info__``.

3.) why doesn't zope scream about it on start up?

Well. It's not wrong at all. It just won't work.

4.) why is the documentation miss leading at that point?

Enhance it! I already did it, see https://pypi.python.org/pypi/plone.behavior#zcml-examples
but seems not well enough.


At the end the simple rule: 

- If you use schema only, the context provides the schema interface (because it stores the values as attributes)
- If you use behavior-adapters, always provide a marker. Its semantically correct. If you use the adapters interface as a marker it might work, but its semantically wrong.
